### ISSUE TITLE
Crash on boot with MYSQL Installed

### ISSUE THREAD

**Issue by Poke5555** [DAQEM/GriefLogger#13]
Minecraft - 1.20.1
Forge - 47.2.0

Grieflogger Forge - 1.20.1-1.1.2
Architectury Forge - 9.1.12
supermartijn642configlib Forge - 1.1.8

When i have "[MySQL JDBC](https://modrinth.com/plugin/mysql-jdbc)" on the server it crashes during boot with this error.
I use MySQL JDBC for bluemap
Every time i reboot the server the mod at the end of the first line changes, in this example its "waystones"

`Exception in thread "main" java.lang.module.ResolutionException: Modules grieflogger and mysql_jdbc export package com.mysql.cj.jdbc.result to module waystones
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)`

**Comment by DAQEM** [comment]
GriefLogger comes with the MySQL JDBC by default. So there is no need for a separate MySQL JDBC mod.

**Comment by Poke5555** [comment]
so i need to use an alternative sql thing for blue map, i spose thats easy enough. thanks for the info :)

**Comment by DAQEM** [comment]
I think if you remove the MySQL JDBC mod, blue map will use the one that comes with GriefLogger, cuz its just a clone of the MySQL JDBC, just like the MySQL JDBC mod.

**Comment by Poke5555** [comment]
bluemap spit out errors saying it couldnt locate sql when i tried that before. 

You can set a "driver-jar" path in the bluemap config, it recommends "mariadb-java-client" which is what i did before reading your reply.
Setting the "driver-jar" path to `mods/grieflogger-1.1.2-forge.jar` also seems to work! thanks again :)

**Comment by DAQEM** [comment]
Awesome, thank you for letting me know!
