### ISSUE TITLE
Mod could connect to the database after restart

### ISSUE THREAD

**Issue by robotter112** [DAQEM/GriefLogger#15]
Minecraft : 1.20.1
Fabric: 0.15.3
Mod Version: 1.1.2

I don't have my database running on the same server as the Minecraft server.
I had to restart the database server for updates but when the database was online again the mod could not connect to the database and the whole log was full of the message:

```
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[grieflogger-1.1.2-fabric.jar:?]
at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[grieflogger-1.1.2-fabric.jar:?]
```

The only thing that helped was a restart of the server, which is of course annoying for the players.

**Comment by DAQEM** [comment]
The mod - at this point on time - only connects to the database at startup and uses this connection for the communication between database and server. I did not add reconnection functionality to the mod because it's very rare for a database to go offline.
