### ISSUE TITLE
mySQL database cannot create entrys

### ISSUE THREAD

**Issue by LordRunner** [DAQEM/GriefLogger#36]
[01:27:16] [GriefLogger thread/ERROR] [co.da.gr.GriefLogger/]: Failed to create table
java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.daqem.grieflogger.database.Database.createTable(Database.java:60) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.daqem.grieflogger.database.repository.MaterialRepository.createTable(MaterialRepository.java:33) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.daqem.grieflogger.database.service.MaterialService.createTable(MaterialService.java:16) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:classloading}
        at com.daqem.grieflogger.GriefLogger.prepareDatabase(GriefLogger.java:61) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:mixin,re:classloading}
        at com.daqem.grieflogger.GriefLogger.lambda$prepareDatabaseAsync$0(GriefLogger.java:52) ~[grieflogger-1.1.4-forge.jar%23135!/:?] {re:mixin,re:classloading}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final] {}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by DAQEM** [comment]
Sorry for the late response. You are using an older version of MySQL. I recommend using 8.4.
