### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by GFoniX** [DAQEM/GriefLogger#5]
(It's a duplicate from the curseforge issues section)

Hello, I wanted to create a Minecraft server with this mods, but it isn't working.

I've configured it as follows:

Architectury 9.1.12 for Forge
GriefLogger 1.0.1 for Forge
SuperMartijn642ConfigLib 1.1.8 for Forge MC 1.20

I'm using Forge version 477.2.20 (I also tested with 47.2.0).
 

However, when I start the server, I encounter the following error:

`
Exception in thread "main" java.lang.module.ResolutionException: Modules org.slf4j and grieflogger export package org.slf4j.spi to module architectury at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900) at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814) at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:754) at java.base/java.lang.module.Resolver.finish(Resolver.java:380) at java.base/java.lang.module.Configuration.<init>(Configuration.java:139) at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
`

It's a problem from my side or not ?

**Comment by DAQEM** [comment]
Version 1.0.2 fixes this issue.

**Comment by DAQEM** [comment]
Oh I didn't release it yet.. My bad.

**Comment by halvors** [comment]
Why are releases not published on CurseForge anymore?

**Comment by DAQEM** [comment]
They are 'Under Manual Review'. Might gave to use the jar form GitHub or Modrinth for now.
